var mongoose = require("mongoose");
var nameSchema = new mongoose.Schema({
  fisrt_name: String,
  last_name: String,
  mobile_number: String,
  address: String,
  email_address: String,
  password: String,
  height: String,
  weight: String,
  occuption: String,
  income: String,
  password: String,
  profile_picture: String,
  father_name: String,
  mother_name: String,
  father_occuption: String,
  father_income: String,
  mother_name: String,
  mother_occuption: String,
  mother_income: String,
  mother_job_profile: String,
  married_brother: String,
  unmarried_brother: String,
  married_sister: String,
  unmarried_sister: String,
  address: String,
  zipcode: String,
  father_job_profile: String,

  job_profile: String,
  verify: { type: Boolean, default: false },
  active: { type: Boolean, default: true },
  create_date: { type: Date, default: new Date() },
  update_date: { type: Date, default: new Date() },
  token: { type: String },
});
module.exports = mongoose.model("user_masters", nameSchema);
